AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Batch processing for dbowland.com

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy
  SmsApiKey:
    Type: String
    Description: API key for sms-queue-api

Mappings:
  EnvironmentMap:
    prod:
      certificate: adce1a21-90b4-4120-8548-111215e582f0
      domainInternal: dbowland-batch-internal.dbowland.com
      lambdaCleanupNumberOfThreads: 4
      lambdaCleanupTable: dbowland-batch-lambda-cleanup
      logStreamFunction: log-subscriber
      project: dbowland-batch-subscriber
      s3BucketChoosee: choosee-lambda
      s3BucketConnections: connections-lambda
      s3BucketDbowlandEast1: dbowland-lambda-east-1
      s3BucketDbowlandEast2: dbowland-lambda-east-2
      s3BucketEmails: emails-lambda
      s3BucketJokes: jokes-lambda
      s3BucketSse: sse-lambda
      schedulerFunction: scheduler-service
      smsApiUrl: https://sms-queue-api.dbowland.com/v1
      zoneId: Z072422417XWM8PIXXSFA
      zooTourSmsNumberOfThreads: 2
      zooTourStatusNumberOfThreads: 5
      zooTourTable: dbowland-batch-zoo-tour
    test:
      certificate: 6a48cba7-feb9-4de5-8cbf-d383140fcdef
      domainInternal: dbowland-batch-internal.bowland.link
      lambdaCleanupNumberOfThreads: 4
      lambdaCleanupTable: dbowland-batch-lambda-cleanup-test
      logStreamFunction: log-subscriber-test
      project: dbowland-batch-test
      s3BucketChoosee: choosee-lambda-test
      s3BucketConnections: connections-lambda-test
      s3BucketDbowlandEast1: dbowland-lambda-east-1-test
      s3BucketDbowlandEast2: dbowland-lambda-east-2-test
      s3BucketEmails: emails-lambda-test
      s3BucketJokes: jokes-lambda-test
      s3BucketSse: sse-lambda-test
      schedulerFunction: scheduler-service-test
      smsApiUrl: https://sms-queue-api.bowland.link/v1
      zoneId: Z01312547RGU1BYKIJXY
      zooTourSmsNumberOfThreads: 2
      zooTourStatusNumberOfThreads: 2
      zooTourTable: dbowland-batch-zoo-tour-test

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for dbowland-batch
      Domain:
        DomainName: !FindInMap [EnvironmentMap, !Ref Environment, domainInternal]
        CertificateArn: !Sub
          - 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${Certificate}'
          - Certificate: !FindInMap [EnvironmentMap, !Ref Environment, certificate]
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !FindInMap [EnvironmentMap, !Ref Environment, zoneId]
        BasePath:
          - /v1

  # Lambda

  LambdaS3Cleanup:
    Type: AWS::Serverless::Function
    Properties:
      Description: Deletes unused lambda files from S3
      Architectures:
        - x86_64
      Handler: src/handlers/s3-lambda-cleanup.s3LambdaCleanupHandler
      Environment:
        Variables:
          S3_LAMBDA_CLEANUP_DAYS_TO_KEEP: 7
          S3_LAMBDA_CLEANUP_TABLE_NAME: !FindInMap [EnvironmentMap, !Ref Environment, lambdaCleanupTable]
          S3_LAMBDA_CLEANUP_NUMBER_OF_THREADS:
            !FindInMap [EnvironmentMap, !Ref Environment, lambdaCleanupNumberOfThreads]
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /s3-lambda-cleanup
            Method: post
            Auth:
              ApiKeyRequired: true
        Scheduled:
          Type: Schedule
          Properties:
            Schedule: 'cron(19 2 ? * 2 *)'
      MemorySize: 1536
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref LambdaCleanupTable
        # Buckets of projects managed by this lambda
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketChoosee]
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketConnections]
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketDbowlandEast1]
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketDbowlandEast2]
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketEmails]
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketJokes]
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, s3BucketSse]
      Runtime: nodejs22.x
      Tags:
        'created-by': 'dbowland-batch'
        'created-for': 'dbowland'
        'environment': !Ref Environment
      Timeout: 180
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/s3-lambda-cleanup.ts

  LambdaS3CleanupLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaS3Cleanup}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'dbowland-batch'
        - Key: 'created-for'
          Value: 'dbowland'
        - Key: 'environment'
          Value: !Ref Environment

  LambdaS3CleanupLogGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref LambdaS3CleanupLogGroup

  ZooTourCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Check for new St Louis Zoo tours
      Architectures:
        - x86_64
      Handler: src/handlers/zoo-tour-check.zooTourCheckHandler
      Environment:
        Variables:
          SMS_API_KEY: !Ref SmsApiKey
          SMS_API_URL: !FindInMap [EnvironmentMap, !Ref Environment, smsApiUrl]
          ZOO_TOUR_SMS_NUMBER_OF_THREADS: !FindInMap [EnvironmentMap, !Ref Environment, zooTourSmsNumberOfThreads]
          ZOO_TOUR_STATUS_NUMBER_OF_THREADS: !FindInMap [EnvironmentMap, !Ref Environment, zooTourStatusNumberOfThreads]
          ZOO_TOUR_TABLE: !FindInMap [EnvironmentMap, !Ref Environment, zooTourTable]
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /check-zoo-tour-status
            Method: post
            Auth:
              ApiKeyRequired: true
      MemorySize: 1536
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref ZooTourTable
      Runtime: nodejs22.x
      Tags:
        'created-by': 'dbowland-batch'
        'created-for': 'zoo-tour'
        'environment': !Ref Environment
      Timeout: 300
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2023'
        Sourcemap: true
        EntryPoints:
          - src/handlers/zoo-tour-check.ts

  ZooTourCheckLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ZooTourCheckLambda}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'dbowland-batch'
        - Key: 'created-for'
          Value: 'zoo-tour'
        - Key: 'environment'
          Value: !Ref Environment

  ZooTourCheckLogGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref ZooTourCheckLogGroup

  ZooTourLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub '${ZooTourCheckLambda.Arn}'
      Principal: events.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/*'

  # Database

  LambdaCleanupTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Project
        Type: String
      TableName: !FindInMap [EnvironmentMap, !Ref Environment, lambdaCleanupTable]
      Tags:
        'created-by': 'dbowland-batch'
        'created-for': 'dbowland'
        'environment': !Ref Environment

  ZooTourTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: TourId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: TourId
          KeyType: HASH
      TableName: !FindInMap [EnvironmentMap, !Ref Environment, zooTourTable]
      Tags:
        - Key: 'created-by'
          Value: 'dbowland-batch'
        - Key: 'created-for'
          Value: 'zoo-tour'
        - Key: 'environment'
          Value: !Ref Environment
